# Generated by Django 4.1.3 on 2022-11-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations.station', verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='stations.station'),
        ),
    ]
